### ISSUE TITLE
In case of restricted content Google Imagen sends "invalid_argument". Expected "content_filter"

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-adapter-vertexai#66]
1. Create a chat based on Google imagen model
2. Ask to generate a picture using words: boy, girl or bomb -> incorrect UI message is received, as FE receives 400 error from BE

![image](https://github.com/epam/ai-dial-adapter-vertexai/assets/111180458/f57d0c2a-90af-4815-8ffd-f4636bcd72be)

[12:43:49.380] ERROR (18): Error while sending chat request to 'imagegeneration@005' [trace_id=ff647949e5ace5bdf7bc77dab989d157, span_id=7b799502d5a26f8e]
    trace_id: "ff647949e5ace5bdf7bc77dab989d157"
    span_id: "7b799502d5a26f8e"
    trace_flags: "01"
    err: {
      "type": "DialAIError",
      "message": "Invalid argument: 400 Image generation failed with the following error: The response is blocked, as it may violate our policies. If you believe this is an error, please send feedback to your account team. Error Code: 58061214",
      "stack":
          DialAIError: Invalid argument: 400 Image generation failed with the following error: The response is blocked, as it may violate our policies. If you believe this is an error, please send feedback to your account team. Error Code: 58061214
              at OpenAIStream (/app/.next/server/pages/api/chat.js:1:6169)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async handler (/app/.next/server/pages/api/chat.js:1:2095)
      "name": "DialAIError",
      "param": "",
      "code": "invalid_argument"
    }

Expected:  "content_filter" to have UI error like
![image](https://github.com/epam/ai-dial-adapter-vertexai/assets/111180458/d81f5f46-3c25-49e6-a1c4-01b1c884c144)

**Comment by VolhaBazhkova** [comment]
Closed as a duplicate of #48
